### ISSUE TITLE
视频结尾会丢帧

### ISSUE THREAD

**Issue by nginnx** [joffychim/mqplayer#1]
首先感谢作者的repo，接入后解决了非常多的兼容性问题
目前发现有个问题是，视频结尾可能丢帧

并且，如果是非常短的只有几帧的视频的话，会无法播放
找到的原因是inputBuffer 已经endOfStream了，outputBuffer还没有
这个时候outputBuffer还需要getFrame，但是decode线程进入wait
然后在VideoRenderer的drainOutputBuffer中就死循环了...

**Comment by joffychim** [comment]
没有发现类似问题，你拉下最新代码看看

**Comment by nginnx** [comment]
最新代码也有问题，我是用的一个6帧的视频做的测试，会一定几率出现无法播放

我还发现了其它几个问题
1.在nexus等一些手机上,video renderer，renderRgb ，绘制bitmap的时候，一帧耗时200，300ms，导致视频严重卡顿
具体和这个issue有关
https://issuetracker.google.com/issues/64882137

2.render rgb ,bitmap scale会出现锯齿

3.supportsFormat方法里不应该支持h265,h265的视频ffmpeg解不出来，应该用ExoPlayer的mediacodec硬解

**Comment by joffychim** [comment]
能提供下这个6帧的视频吗？我邮箱joffychim@163.com
1、绘制慢的问题：稍后我改下直接使用opengl着色器来绘制
3、h265还没做支持，晚点再看看

**Comment by nginnx** [comment]
6帧的视频
https://github.com/nginnx/assets/blob/master/video.mp4

**Comment by joffychim** [comment]
hi @nginnx 6帧视频播放错误的问题，最新的提交已经修复了，H265也支持了哈。绘制慢的问题，我已经改为使用着色器自己画yuv，不再使用canvas画bitmap，应该不会出现某些手机绘制时间过长的问题了。
