### ISSUE TITLE
Question：whether the libffmpeg.so has optimized with neno?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [joffychim/mqplayer#2]
I use your library to play files on some devices, it's not drop frames. But I compile the ffmpeg so by myself, it drop frames seriously on the same device.

I just use the build script provided by ExoPlayer FFmpeg extension.
```
./configure 
--libdir=android-libs/armeabi-v7a 
--arch=arm --cpu=armv7-a 
--cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi 4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-" 
--sysroot="${NDK_PATH}/platforms/android-9/arch-arm/" 
--extra-cflags="-march=armv7-a -mfloat-abi=softfp"
 --extra-ldflags="-Wl,--fix-cortex-a8" 
--extra-ldexeflags=-pie 
--target-os=android --disable-static --enable-shared --disable-doc --disable-programs --disable-everything --disable-avdevice --disable-avformat --disable-swscale --disable-postproc --disable-avfilter --disable-symver --disable-swresample 
--enable-avresample --enable-decoder=vorbis --enable-decoder=opus --enable-decoder=flac --enable-decoder=mp3 --enable-decoder=h264 --enable-decoder=hevc
```
I just add h264/hevc decoder.  If possible, help you could give a build script, so we could easily compile the dynamic library. Thanks!

**Comment by joffychim** [comment]
#!/bin/bash

. abi_settings.sh $1 $2 $3

pushd ffmpeg

case $1 in
  armeabi-v7a | armeabi-v7a-neon)
    CPU='cortex-a8'
  ;;
  x86)
    CPU='i686'
  ;;
esac

make clean

./configure \
--target-os="$TARGET_OS" \
--cross-prefix="$CROSS_PREFIX" \
--arch="$NDK_ABI" \
--cpu="$CPU" \
--enable-runtime-cpudetect \
--enable-neon \
--sysroot="$NDK_SYSROOT" \
--disable-bzlib \
--disable-sse \
--disable-avdevice \
--disable-linux-perf \
\
--disable-filters \
--enable-filter=aformat \
--enable-filter=amix \
--enable-filter=palettegen,paletteuse \
--enable-filter=crop \
--enable-filter=anull \
--enable-filter=aresample \
--enable-filter=trim \
--enable-filter=split \
--enable-filter=format \
--enable-filter=null \
--enable-filter=overlay \
--enable-filter=scale \
--enable-filter=concat \
--enable-filter=setsar \
--enable-filter=amovie \
--enable-filter=volume \
--enable-filter=hstack \
--enable-filter=vstack \
--enable-filter=movie \
--enable-filter=blend \
--enable-filter=setpts,pad,overlay \
\
--disable-decoders \
--disable-encoders \
--enable-decoder=h264 \
--enable-decoder=aac \
--enable-decoder=mp3 \
--enable-decoder=png,mjpeg \
--enable-encoder=png,mjpeg,gif \
--enable-encoder=aac \
--enable-encoder=h264 \
--enable-encoder=libx264 \
\
--disable-muxers \
--disable-demuxers \
--enable-muxer=mp4 \
--enable-demuxer=h264 \
--enable-demuxer=mp3 \
--enable-demuxer=aac \
--enable-demuxer=mov \
--enable-demuxer=concat \
--enable-muxer=gif \
--enable-demuxer=image2 \
--enable-muxer=image2 \
--enable-muxer=h264 \
--enable-demuxer=image_png_pipe \
--enable-demuxer=image_png_pipe \
--disable-protocols \
--enable-protocol=file \
\
--disable-parsers \
--enable-parser=aac \
--enable-parser=h264 \
\
--disable-bsfs \
--enable-bsf=aac_adtstoasc \
--enable-bsf=h264_mp4toannexb \
\
--enable-pic \
--enable-libx264 \
--enable-pthreads \
--enable-swscale \
--disable-debug \
--enable-version3 \
--enable-hardcoded-tables \
--disable-ffplay \
--disable-ffprobe \
--enable-cross-compile \
--enable-gpl \
--disable-yasm \
--enable-asm \
--enable-inline-asm \
--enable-optimizations \
--enable-small \
--disable-doc \
--disable-ffmpeg \
--disable-shared \
--enable-static \
--pkg-config="${2}/ffmpeg-pkg-config" \
--prefix="${2}/build/${1}" \
--extra-cflags="-I${TOOLCHAIN_PREFIX}/include $CFLAGS" \
--extra-ldflags="-L${TOOLCHAIN_PREFIX}/lib $LDFLAGS" \
--extra-libs="-lm" \
--extra-cxxflags="$CXX_FLAGS" || exit 1

make -j${NUMBER_OF_CORES} && make install


# 合并到ffmpeg so库
export PREBUILT=${ANDROID_NDK}/toolchains/arm-linux-androideabi-${NDK_TOOLCHAIN_ABI_VERSION}/prebuilt/${PREBUILD_TOOL}
export PLATFORM=${ANDROID_NDK}/platforms/android-${ANDROID_API_VERSION}/arch-arm
export FFMPEG_DIR=${BASEDIR}/ffmpeg
export LIBX264=${TOOLCHAIN_PREFIX}/lib/libx264.a

FF_MODULE_DIRS="compat libavcodec libavfilter libavformat libavutil libswresample libswscale libpostproc"
FF_ASSEMBLER_SUB_DIRS="arm neon"

rm ./libavcodec/aacps_tablegen.o
rm ./libavcodec/cbrt_tablegen.o
rm ./libavcodec/cos_tablegen.o
rm ./libavcodec/sinewin_fixed_tablegen.o
rm ./libavcodec/sinewin_tablegen.o
rm ./libavcodec/mpegaudio_tablegen.o

F_C_OBJ_FILES=
FF_ASM_OBJ_FILES=
for MODULE_DIR in $FF_MODULE_DIRS
do
    C_OBJ_FILES="$MODULE_DIR/*.o"
    if ls $C_OBJ_FILES 1> /dev/null 2>&1; then
        echo "link $MODULE_DIR/*.o"
        FF_C_OBJ_FILES="$FF_C_OBJ_FILES $C_OBJ_FILES"
    fi

    for ASM_SUB_DIR in $FF_ASSEMBLER_SUB_DIRS
    do
        ASM_OBJ_FILES="$MODULE_DIR/$ASM_SUB_DIR/*.o"
        if ls $ASM_OBJ_FILES 1> /dev/null 2>&1; then
            echo "link $MODULE_DIR/$ASM_SUB_DIR/*.o"
            FF_ASM_OBJ_FILES="$FF_ASM_OBJ_FILES $ASM_OBJ_FILES"
        fi
    done
done


CC="$PREBUILT/bin/arm-linux-androideabi-gcc-${NDK_TOOLCHAIN_ABI_VERSION}"
$CC --sysroot=$PLATFORM \
    -L$PLATFORM/usr/lib \
    -lm -lz -shared -Wl,--no-undefined -Wl,-z,noexecstack \
    -Wl,-soname,libffmpeg.so \
    $FF_C_OBJ_FILES \
    $FF_ASM_OBJ_FILES \
    $LIBX264 \
    -o $PLATFORM/usr/libffmpeg.so


cp $PLATFORM/usr/libffmpeg.so  ../libffmpeg.so
rm -f $PLATFORM/usr/libffmpeg.so
rm -rf ${TOOLCHAIN_PREFIX}

popd

**Comment by joffychim** [comment]
`#!/bin/bash

. abi_settings.sh $1 $2 $3

pushd ffmpeg

case $1 in
  armeabi-v7a | armeabi-v7a-neon)
    CPU='cortex-a8'
  ;;
  x86)
    CPU='i686'
  ;;
esac

make clean

./configure \
--target-os="$TARGET_OS" \
--cross-prefix="$CROSS_PREFIX" \
--arch="$NDK_ABI" \
--cpu="$CPU" \
--enable-runtime-cpudetect \
--enable-neon \
--sysroot="$NDK_SYSROOT" \
--disable-bzlib \
--disable-sse \
--disable-avdevice \
--disable-linux-perf \
\
--disable-filters \
--enable-filter=aformat \
--enable-filter=amix \
--enable-filter=palettegen,paletteuse \
--enable-filter=crop \
--enable-filter=anull \
--enable-filter=aresample \
--enable-filter=trim \
--enable-filter=split \
--enable-filter=format \
--enable-filter=null \
--enable-filter=overlay \
--enable-filter=scale \
--enable-filter=concat \
--enable-filter=setsar \
--enable-filter=amovie \
--enable-filter=volume \
--enable-filter=hstack \
--enable-filter=vstack \
--enable-filter=movie \
--enable-filter=blend \
--enable-filter=setpts,pad,overlay \
\
--disable-decoders \
--disable-encoders \
--enable-decoder=h264 \
--enable-decoder=aac \
--enable-decoder=mp3 \
--enable-decoder=png,mjpeg \
--enable-encoder=png,mjpeg,gif \
--enable-encoder=aac \
--enable-encoder=h264 \
--enable-encoder=libx264 \
\
--disable-muxers \
--disable-demuxers \
--enable-muxer=mp4 \
--enable-demuxer=h264 \
--enable-demuxer=mp3 \
--enable-demuxer=aac \
--enable-demuxer=mov \
--enable-demuxer=concat \
--enable-muxer=gif \
--enable-demuxer=image2 \
--enable-muxer=image2 \
--enable-muxer=h264 \
--enable-demuxer=image_png_pipe \
--enable-demuxer=image_png_pipe \
--disable-protocols \
--enable-protocol=file \
\
--disable-parsers \
--enable-parser=aac \
--enable-parser=h264 \
\
--disable-bsfs \
--enable-bsf=aac_adtstoasc \
--enable-bsf=h264_mp4toannexb \
\
--enable-pic \
--enable-libx264 \
--enable-pthreads \
--enable-swscale \
--disable-debug \
--enable-version3 \
--enable-hardcoded-tables \
--disable-ffplay \
--disable-ffprobe \
--enable-cross-compile \
--enable-gpl \
--disable-yasm \
--enable-asm \
--enable-inline-asm \
--enable-optimizations \
--enable-small \
--disable-doc \
--disable-ffmpeg \
--disable-shared \
--enable-static \
--pkg-config="${2}/ffmpeg-pkg-config" \
--prefix="${2}/build/${1}" \
--extra-cflags="-I${TOOLCHAIN_PREFIX}/include $CFLAGS" \
--extra-ldflags="-L${TOOLCHAIN_PREFIX}/lib $LDFLAGS" \
--extra-libs="-lm" \
--extra-cxxflags="$CXX_FLAGS" || exit 1

make -j${NUMBER_OF_CORES} && make install


# 合并到ffmpeg so库
export PREBUILT=${ANDROID_NDK}/toolchains/arm-linux-androideabi-${NDK_TOOLCHAIN_ABI_VERSION}/prebuilt/${PREBUILD_TOOL}
export PLATFORM=${ANDROID_NDK}/platforms/android-${ANDROID_API_VERSION}/arch-arm
export FFMPEG_DIR=${BASEDIR}/ffmpeg
export LIBX264=${TOOLCHAIN_PREFIX}/lib/libx264.a

FF_MODULE_DIRS="compat libavcodec libavfilter libavformat libavutil libswresample libswscale libpostproc"
FF_ASSEMBLER_SUB_DIRS="arm neon"

rm ./libavcodec/aacps_tablegen.o
rm ./libavcodec/cbrt_tablegen.o
rm ./libavcodec/cos_tablegen.o
rm ./libavcodec/sinewin_fixed_tablegen.o
rm ./libavcodec/sinewin_tablegen.o
rm ./libavcodec/mpegaudio_tablegen.o

F_C_OBJ_FILES=
FF_ASM_OBJ_FILES=
for MODULE_DIR in $FF_MODULE_DIRS
do
    C_OBJ_FILES="$MODULE_DIR/*.o"
    if ls $C_OBJ_FILES 1> /dev/null 2>&1; then
        echo "link $MODULE_DIR/*.o"
        FF_C_OBJ_FILES="$FF_C_OBJ_FILES $C_OBJ_FILES"
    fi

    for ASM_SUB_DIR in $FF_ASSEMBLER_SUB_DIRS
    do
        ASM_OBJ_FILES="$MODULE_DIR/$ASM_SUB_DIR/*.o"
        if ls $ASM_OBJ_FILES 1> /dev/null 2>&1; then
            echo "link $MODULE_DIR/$ASM_SUB_DIR/*.o"
            FF_ASM_OBJ_FILES="$FF_ASM_OBJ_FILES $ASM_OBJ_FILES"
        fi
    done
done


CC="$PREBUILT/bin/arm-linux-androideabi-gcc-${NDK_TOOLCHAIN_ABI_VERSION}"
$CC --sysroot=$PLATFORM \
    -L$PLATFORM/usr/lib \
    -lm -lz -shared -Wl,--no-undefined -Wl,-z,noexecstack \
    -Wl,-soname,libffmpeg.so \
    $FF_C_OBJ_FILES \
    $FF_ASM_OBJ_FILES \
    $LIBX264 \
    -o $PLATFORM/usr/libffmpeg.so


cp $PLATFORM/usr/libffmpeg.so  ../libffmpeg.so
rm -f $PLATFORM/usr/libffmpeg.so
rm -rf ${TOOLCHAIN_PREFIX}

popd
`

**Comment by joffychim** [comment]
ffmpeg library's build script:
[ffmpeg.zip](https://github.com/joffychim/mqplayer/files/2863375/ffmpeg.zip)

**Comment by Romantic-LiXuefeng** [comment]
Thanks! The reason of dropping frames seriously is only use one thread to decode with ffmpeg.
     ```av_dict_set_int(&opts, "threads", cpuCoreNum, 0);```
when I set like this, it doesn't drop frames. 
Thanks again! Help you can explain the build script. Which line is key statement to optimize with neno.

I don't understand why using a frame cache buffer. Help you can explain why .
`private FfmpegOutputBuffer nextOutputBuffer;`

**Comment by Romantic-LiXuefeng** [comment]
If possible, You can contact me with wechat [LXF15373699045](url). I hope to communicate with you.
