### ISSUE TITLE
demo播放高清视频时绿屏

### ISSUE THREAD

**Issue by xyoye** [joffychim/mqplayer#3]
感谢您提供的demo，目前在测试一些视频的时候遇到了绿屏的问题

这是播放的视频格式：
![Screenshot_2019-04-25-14-35-21-572_com mxtech vid](https://user-images.githubusercontent.com/23527777/56714456-71cc0800-6767-11e9-83a8-58e15ff83228.png)

demo的播放效果
![Screenshot_2019-04-25-14-41-05-222_com moqan mqpl](https://user-images.githubusercontent.com/23527777/56714765-6af1c500-6768-11e9-955b-20710da284d1.png)

mxplayer的播放效果
![Screenshot_2019-04-25-14-41-25-088_com mxtech vid](https://user-images.githubusercontent.com/23527777/56714782-747b2d00-6768-11e9-93a7-15c9e1909b38.png)

使用exoplayer的默认的mediacodec解码则无法播放。所以在找ffmpeg的解码器，绿屏这个不知这是什么原因导致的，有什么解决办法吗？

**Comment by joffychim** [comment]
能提供下视频吗 我看看什么问题

**Comment by xyoye** [comment]
> 能提供下视频吗 我看看什么问题

这是视频的百度云链接
链接: https://pan.baidu.com/s/1ESnLkuv1sjHP_hP2-YLxiw 提取码: xv16

**Comment by joffychim** [comment]
@xyoye 已修复。

**Comment by kuailedeadai** [comment]
您好，请教以下，高码率的视频您是如何解决的？谢谢
